### ISSUE TITLE
Add Azure storage provider integration tests to CI build

### ISSUE THREAD

**Issue by aslotte** [aslotte/MLOps.NET#102]
**Is your feature request related to a problem? Please describe.**
We will need to run any Azure storage provider tests in the CI pipeline

**Describe the solution you'd like**
Add Azure integration tests to CI build, this will include adding a secret with the connection string to a storage account to use.

**Comment by Brett-Parker** [comment]
Has this not already been done? MLOps.NET\.github\workflows\integration-tests-azure.yml @aslotte

**Comment by aslotte** [comment]
It sure has! Closing issue.
