### ISSUE TITLE
Add support for MLOps.NET.SqlServer

### ISSUE THREAD

**Issue by aslotte** [aslotte/MLOps.NET#103]
**Is your feature request related to a problem? Please describe.**
Many organizations will want to run MLOps.NET using their on-premise SQL Server instances.

**Describe the solution you'd like**
Add ability to store result in SQL Server

**Comment by CodeItQuick** [comment]
Hey working on this one, you can assign me if you want

**Comment by aslotte** [comment]
Thanks @CodeItQuick! Let me know if you need any help, appreciate it!

**Comment by aslotte** [comment]
Hi @CodeItQuick - I'm going to be working on this during my stream today, but I'm happy to assist you get started with another issue if you would like.

**Comment by CodeItQuick** [comment]
What time do you stream at? I'm good with you getting it started/working on it, I can take over at some point
