### ISSUE TITLE
Separate MLOpsContext into catalogues

### ISSUE THREAD

**Issue by aslotte** [aslotte/MLOps.NET#104]
**Is your feature request related to a problem? Please describe.**
The MLOpsContext is quickly growing. To ensure we have a structure we may want to separate it out into a structure similar to MLContext.

**Describe the solution you'd like**
The MLContext in ML.NET has clear catalogs where one can find a feature. I suggest we break the functionality into separate catalogues that live as properties on the MLOpsContext

- Experiment (create/get experiments)
- Run (create/get runs)
- Data (can be used to track the data used for training later)
- Evaluation (log metrics etc.)
- Model (upload model, download model...)
- Transform/Training? (track hyper-parameters)

**Comment by aslotte** [comment]
@lqdev  / @dcostea  / @AnoojNair  / @shanranm  / @ssa3512  - would like your input on this issue. MLContext in ML.NET has a very clean divide into so-called catalogues where you can find operations. The more this tool evolves, the more I realize that we in many ways are tracking a mirror image of what the tool is doing. Therefore, it may make sense to design the MLOpsContext similarly to the MLContext (where it makes sense) so that it's easy to get started with. 

Would welcome your thoughts.

**Comment by AnoojNair** [comment]
@aslotte like this idea a lot. Catalogues would make things much more discoverable as it grows.

**Comment by shanranm** [comment]
Yes, I too like it! Very much consistent with MLContext behavior, makes it more readable.
