### ISSUE TITLE
Add README to Examples

### ISSUE THREAD

**Issue by luisquintanilla** [aslotte/MLOps.NET#105]
**Is your feature request related to a problem? Please describe.**

Currently it's not clear what the intent of the Examples is or how users should go about running them.

**Describe the solution you'd like**

Add README with instructions how to set up and run the sample.

**Comment by luisquintanilla** [comment]
Assignt to @lqdev

**Comment by aslotte** [comment]
@lqdev - not sure if it makes sense but I added a wiki page where I think some of this can be added to: https://github.com/aslotte/MLOps.NET/wiki/Getting-Started

**Comment by lqdev** [comment]
@aslotte. That makes sense. I'll look at the examples and add to them

**Comment by aslotte** [comment]
Examples have been added to the readme file so I'm closing this issue.
