### ISSUE TITLE
Add building our example repo as part of the CI build

### ISSUE THREAD

**Issue by aslotte** [aslotte/MLOps.NET#110]
**Is your feature request related to a problem? Please describe.**
If we make breaking API changes our example repo will break without us knowing it.

**Describe the solution you'd like**
Add a new workflow file that can be run as part of the CI build to find this. The workflow file should build the example solution, and we probably should update the example solutions to pull directly from our Github feed?

**Comment by CodeItQuick** [comment]
Interested in this one
