### ISSUE TITLE
Add ability to use AWS S3 as ModelRepository

### ISSUE THREAD

**Issue by aslotte** [aslotte/MLOps.NET#112]
**Is your feature request related to a problem? Please describe.**
It would be cool to add S3 support for the model repository

**Describe the solution you'd like**
Add AWS S3 implementation of IModelRepository

**Describe alternatives you've considered**

**Additional context**

**Comment by AnoojNair** [comment]
@aslotte ,Is this up for grabs?

**Comment by aslotte** [comment]
It sure is. I was thinking we can add an `MLOps.NET.AWS` package for this.
