### ISSUE TITLE
Add ability to configure IMetaDataStore and IModelRepository separately 

### ISSUE THREAD

**Issue by aslotte** [aslotte/MLOps.NET#114]
**Is your feature request related to a problem? Please describe.**
Currently, the consumer has to pick either Azure or SQLite for both the metadata and the model repository. But there could be cases where you would like to mix and match, e.g. local storage for models but Azure for the meta data.

**Describe the solution you'd like**
Add the ability to configure the IMetaDataStore and IModelRepository seprate in the MLOpsBuilder and related extension methods.

**Comment by ssa3512** [comment]
Should we move the local file storage model repository into the main library? It seems like that could be used by several different implementations (SQLite, SQLServer) and doesn’t carry many dependencies with it.

**Comment by aslotte** [comment]
@ssa3512 I think that makes a lot of sense. No real need to create `MLOps.NET.LocalFileShare`, as that seems more confusing to me. Better as you say to pull that in to the main package.

**Comment by aslotte** [comment]
This issue has been resolved.
