### ISSUE TITLE
Add migrate ability for SQLite and SQL Server schema

### ISSUE THREAD

**Issue by aslotte** [aslotte/MLOps.NET#120]
**Is your feature request related to a problem? Please describe.**
When we update the schema, e.g. add a new property, our SQLite implemention is out of sync.

**Describe the solution you'd like**
Add ability to automatically migrate the schema.

**Describe alternatives you've considered**

**Additional context**

**Comment by Brett-Parker** [comment]
Could we do something like this?

```
        if (!(Database.EnsureCreated()))
        {
            Database.Migrate();
        }   
```
EnsureCreated returns true if it created a DB and false if it already exists.   

ref: https://docs.microsoft.com/en-us/dotnet/api/microsoft.entityframeworkcore.infrastructure.databasefacade.ensurecreated?view=efcore-3.1

Or is this in relation to something else? (Point me in the right direction if possible)

**Comment by aslotte** [comment]
I think we should be able to replace `Databsae.EnsureCreated()` with `Database.Migrate()`. I think `Migrate()` does both. Needs to be tested by changing the schema (e.g. adding a column to an entity) and running an integration test. We also want to confirm that the data is not wiped when performing the migration.

**Comment by aslotte** [comment]
See comments on #201. This probably is a tiny bit tricker than expected (shouldn't be too difficult though). We just need to support migrations and add them for each db schema change we do. I recommend we hold off on this feature until we're close to a v1.0 release as it will only really be needed once we go out of beta.

**Comment by aslotte** [comment]
We probably need separate migrations for SQL Server and SQLite. Still have to figure out how this is best done.
