### ISSUE TITLE
Add an MLOps.NET dotnet global tool

### ISSUE THREAD

**Issue by aslotte** [aslotte/MLOps.NET#121]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**
It would be interesting to have a dotnet global tool for some of the functionality in MLOps.NET so it can be automated via the CLI. That could include various deployment scenarios. 

A dotnet global tool is a command line nuget package. This is a good reference: https://www.dotnetcurry.com/dotnet/1495/dotnet-core-global-tools

**Describe alternatives you've considered**

**Additional context**

**Comment by shanranm** [comment]
This cli is for fetching the data? As an alternative to the blazer UI?
I don't see how we can leverage for anything else.

**Comment by aslotte** [comment]
I think the idea was to have the CLI tool as a global dotnet tool that could be used within a GitHub Action for certain operations (e.g. upload model, create an experiment/run, link to git hub commit etc.), but I believe @lqdev may be able to elaborate further.

**Comment by lqdev** [comment]
The purpose of this would be similar to that of MLFlow CLI. With the CLI, you can perform most tracking, model management, and deployment functions:

For reference, see the following link: https://www.mlflow.org/docs/latest/cli.html#

**Comment by aslotte** [comment]
I'm excited about this feature. I think creating a MLOps.NET.CLI nuget package that can be used a `dotnet global tool` will be really nice and a great extension of this library.
