### ISSUE TITLE
Rename the master branch to main

### ISSUE THREAD

**Issue by aslotte** [aslotte/MLOps.NET#122]
**Is your feature request related to a problem? Please describe.**
The name of the master branch is offensive 

**Describe the solution you'd like**
We should rename the master branch to main.

**Comment by mbrdev** [comment]
A quick guide on how to do this: https://www.hanselman.com/blog/EasilyRenameYourGitDefaultBranchFromMasterToMain.aspx

I'm not sure how to turn this into a pull request though.

**Comment by aslotte** [comment]
This issue has been completed and the default branch is now `main`. The old `master` branch has been removed.
