### ISSUE TITLE
Refactor SQLite implementation to use LocalDbContextFactory

### ISSUE THREAD

**Issue by aslotte** [aslotte/MLOps.NET#135]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**
Similarly to the SQLServer implementation, it would be nice if we refactored the current solution to use a LocalDbContextFactory

**Comment by CodeItQuick** [comment]
Can you assign me to this one?

**Comment by aslotte** [comment]
@CodeItQuick thank you, assigned! A week would be great, but no rush. Let me know if I can help in any way, it should be very similar to what we did today during the stream.

**Comment by aslotte** [comment]
This has been accomplished as part of #196.
