### ISSUE TITLE
The SQLite Storage Provider is creating duplicate experiments

### ISSUE THREAD

**Issue by aslotte** [aslotte/MLOps.NET#136]
**Describe the bug**
If we use the SQLite storage provider, it will create duplicate experiments if one already exists. The expected behavior is that it will just return existing one. We should add an integration test to assert this.

**To Reproduce**
1. Call `CreateExperimentAsync("test")` twice

**Expected behavior**
No duplicate experiments (with the same name) should be created. Instead, we should return the ID of the existing experiment.

The current implementation is as follows, and we need to change it to check if the experiment already exists.

```
        public async Task<Guid> CreateExperimentAsync(string name)
        {
            using (var db = new LocalDbContext())
            {
                var experiment = new Experiment(name);
                await db.Experiments.AddAsync(experiment);
                await db.SaveChangesAsync();
                
                return experiment.Id;
            }
        }
```

**Comment by mbrdev** [comment]
I'll give this one a go.

**Comment by aslotte** [comment]
Thanks @mbrdev! Let me know if I can help in any way.
