### ISSUE TITLE
Create structure for integration tests on multiple levels

### ISSUE THREAD

**Issue by aslotte** [aslotte/MLOps.NET#138]
**Is your feature request related to a problem? Please describe.**
We currently have a mix of automated tests and we would need to decide on what layers we should test

**Describe the solution you'd like**
Our unit test projects are perfect, not much to do there. However our integration test project right now are good, but some test e.g. the meta data store directly while others go all the way from the MLOpsContext. I think both levels are valid, and should be tested, but we may want to structure our tests better to make sure that's the case, and add missing tests where possible (currently this is scoped for SQLite and SQLServer.

The ask:
- Create integration tests just for the respective metadata stores
- Create integration tests from the MLOpsContext for a given implementation

We have a lot of the tests already, this would be mostly cleaning some of them up and adding others were missing

**Comment by shanranm** [comment]
And please move all the test projects under a folder. It's pretty confusing keeping everything under src folder

**Comment by aslotte** [comment]
@shanranm if you open the solution up in Visual Studio, the internal structure is actually already set up like that: 

![image](https://user-images.githubusercontent.com/30201569/85235254-85154a80-b3e1-11ea-9c07-ba4d0dd0c365.png)

**Comment by shanranm** [comment]
Not in VS but the folder structure itself, I like to use VSCode for non-heavy projects, and it's pretty confusing! We still have SQL, Dynamo implementations coming up and they will add 6 more projects!

<img width="380" alt="Screenshot 2020-06-22 at 2 43 32 AM" src="https://user-images.githubusercontent.com/52841446/85235395-2fb55980-b432-11ea-874e-e170be16488b.png">

**Comment by aslotte** [comment]
Gotcha, thank you for clarifying. That make sense to include in this issue.

**Comment by aslotte** [comment]
I consider this to have been completed as part of #200
