### ISSUE TITLE
Add documentation on how the library can be used

### ISSUE THREAD

**Issue by aslotte** [aslotte/MLOps.NET#14]

**Comment by shanranm** [comment]
if you could put in this piece, it'd be easier for contributors (who doesn't know ml) to understand

**Comment by aslotte** [comment]
Makes sense @shanranm, I'll see what I can do

**Comment by shanranm** [comment]
I'd suggest creating a small ml project under tests which the library can run against, will also serve as integration tests

**Comment by aslotte** [comment]
It's actually being worked on in #19 by Sammy. I'm also going to include another simple ML project under an Examples folder later, which hopefully will help a bit :)

**Comment by jwood803** [comment]
Is this mainly updating the "Getting Started" section of the README?

**Comment by aslotte** [comment]
I was thinking an entire new markdown file walking though various things we can do and how, e.g. log metrics, upload models, use both Azure and SQLite etc. 

More like an API doc I guess

**Comment by aslotte** [comment]
Given that we have examples in the Readme file and a sample solution, I'm going to close this issue.
