### ISSUE TITLE
Update examples for 0.1.3-beta

### ISSUE THREAD

**Issue by aslotte** [aslotte/MLOps.NET#145]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**
Update our existing examples to match 0.1.3-beta

**Comment by Brett-Parker** [comment]
Latest build is marked as 0.2.29-alpha. Happy to update examples to that? If so, please assign this to me.

**Comment by aslotte** [comment]
That's correct, 0.1.0 was a mistake... :) The one previous was actually not tagged as a release in GitHub, that's why you don't have it to compare with.

**Comment by aslotte** [comment]
Could still be time for a new release soon, but would like to get a bit more test coverage on some areas (integration and unit tests) before then.
