### ISSUE TITLE
[Data] Add ability to calculate and capture data distribution

### ISSUE THREAD

**Issue by aslotte** [aslotte/MLOps.NET#162]
**Is your feature request related to a problem? Please describe.**
For certain scenarios, e.g. classification models, the distribution of the data is important as it may greatly affect the model performance.

**Describe the solution you'd like**
It would be cool if we could have the ability to calculate and track the data distribution of an IDataView (e.g. number of unique values in each column).

**Comment by AnoojNair** [comment]
@aslotte , Should this be performed as part of LogData for each column in DataView or a seperate operation after LogData for columns that required to be investigated?

**Comment by aslotte** [comment]
Given that this may only make sense for certain ML tasks, e.g. classification etc, let's add it as a separate method `LogDataDistribution`. E.g. for regression and forecasting tasks we probably don't care too much about doing this, while for classification it's super important.

**Comment by AnoojNair** [comment]
@aslotte , I am thinking of a separate entity for DataDistribution and will be  part of the DataColumn as a property  

   public List<DataDistribution> Distribution { get; set; } = new List<DataDistribution>();

 which will store each unique value for the column along with count of that value. Do you think if that's ok ? 

         public Guid DataColumnId { get; set; }

        public string Value { get; set; }

        public int Count { get; set; }

**Comment by aslotte** [comment]
I think you're on the right track @AnoojNair, I can't think of a better solution :)
