### ISSUE TITLE
[Data] Add the ability to create a unique hash for a dataset

### ISSUE THREAD

**Issue by aslotte** [aslotte/MLOps.NET#164]
**Is your feature request related to a problem? Please describe.**
To understand if data has changed in between the training of two models, we'll need some ability to take a snapshot of the data. This is of course really difficult.

**Describe the solution you'd like**
Add the ability to create a computed hash for a dataset and store that in associated to a run.

**Comment by AnoojNair** [comment]
@aslotte , Something like this may be?

https://docs.microsoft.com/en-us/dotnet/api/system.security.cryptography.hashalgorithm.computehash?view=netcore-3.1#System_Security_Cryptography_HashAlgorithm_ComputeHash_System_IO_Stream_

mlContext.Data has a function to create a binary stream which can be passed into this algo.

**Comment by aslotte** [comment]
Nice, an option for sure @AnoojNair. Worth taking a look at.

**Comment by AnoojNair** [comment]
@aslotte ,How will this hash be used once it is saved. Is this an indicator that the dataset has changed, but not sure what changed?

**Comment by aslotte** [comment]
My first inclination is that it would be used to tell if the data for two models has changed or not. However, I haven't had a chance to dive into the data versioning world, so it is possible there's a better way to solve this. We could try to keep it simple for now though and use the hash to understand if the data is different for now.
