### ISSUE TITLE
Add docs folder to structure

### ISSUE THREAD

**Issue by Brett-Parker** [aslotte/MLOps.NET#179]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**
Clear concise documentation 

**Describe alternatives you've considered**
Left as is

**Additional context**
Thinking along the lines of: https://github.com/dotnet/machinelearning/tree/master/docs

**Comment by Brett-Parker** [comment]
@aslotte agree? Input needed.

**Comment by aslotte** [comment]
We can certainly do that. I was thinking we could build on the Wiki section instead and add a link from our Readme file to it (in addition to some simple examples there) https://github.com/aslotte/MLOps.NET/wiki

What do you think?

**Comment by Brett-Parker** [comment]
@aslotte sounds good to me :) I'll try and add things there. There are other tickets covering documentation, this one was only around the folder structure. I'll close this one.
