### ISSUE TITLE
Add description to saved model

### ISSUE THREAD

**Issue by Brett-Parker** [aslotte/MLOps.NET#220]
**Describe the solution you'd like**
There should be the ability to add a description to a trained model for deployment.

**Additional context**
 Its likely that the person training and deploying the model is not the same person consuming the model. The description can be a simple string field populated by the model trainer.

**Comment by aslotte** [comment]
Are you envisioning this information to live on the `Experiment` or the `RegisteredModel`? E.g. do you see a need for them to be different?

**Comment by Brett-Parker** [comment]
@aslotte good question. I think its only relevant on the RegisteredModel.

**Comment by aslotte** [comment]
I think that's fair :)
