### ISSUE TITLE
Add ability to log metrics of a regression model

### ISSUE THREAD

**Issue by aslotte** [aslotte/MLOps.NET#25]
Add the ability to pass in the evaluation result from a regression model and automatically log all values as key-value pairs

**Comment by mbrdev** [comment]
@aslotte, I'll give this one a go if you want to assign to me.

**Comment by aslotte** [comment]
Thanks @mbrdev. It's possible that what we already have to track metrics is sufficient, but it would be awesome if you could have a look and see what we could be missing that's specific for the regression scenario (e.g. just like a ConfusionMatrix is specific for classification)

**Comment by Brett-Parker** [comment]
As a part of #186 I was looking to see if there was anything missing on the metrics side. I don't think there is for regression. The current method tracks most metrics well!

**Comment by aslotte** [comment]
Given that we think that we currently captures all values, I'm going to close this issue.
