### ISSUE TITLE
Add IsProduction flag on DeploymentTarget

### ISSUE THREAD

**Issue by aslotte** [aslotte/MLOps.NET#251]
**Is your feature request related to a problem? Please describe.**
Our deployment targets can have random names, based on what the users wants to name them. This is awesome but makes it difficult to e.g. write a method to fetch the evaluation metrics of the model in production.

**Describe the solution you'd like**
I propose we add a flag on deployment target for IsProduction that can be optionally set (default to false) when creating a deployment target.

**Comment by willvelida** [comment]
@aslotte all good if I close this issue?

**Comment by aslotte** [comment]
Please do!
