### ISSUE TITLE
Add skeleton Blazor WebAssembly client

### ISSUE THREAD

**Issue by aslotte** [aslotte/MLOps.NET#26]
Add skeleton Blazor WebAssembly client that we can continue to build upon in smaller tickets.

**Comment by aslotte** [comment]
While out running I thought of a way I think we should design this for the out-most reusability.

We should continue to build out not only write methods in MLOps.NET, MLOps.NET.Azure and MLOps.NET.SQLite, but also start building out read methods.

E.g. we would most likely want methods such as get all experiments, get all runs etc. 

What we then could do is use both this SDK client in the Blazor WebAssembly app and let the Blazor app be purely UI and display logic. Writing this down in this ticket to remember it but will add a Visio diagram shortly.

**Comment by AnoojNair** [comment]
Hi @aslotte ,

just curious how this will be consumed. Will this be a part of the same nuget package?

**Comment by aslotte** [comment]
Great question so in my mind it will be:
- A separate solution, part of the same repo
- The Blazor client will consume our Nuget SDK for the heavy lifting
- The Blazor client will be eventually packaged in a Docker container so for the end user they will consume this client by pulling the image from e.g. Docker Hub setting the connectionstring and starting the container.

**Comment by aslotte** [comment]
This is a good resource to get started with Blazor WebAssembly: https://devblogs.microsoft.com/aspnet/blazor-webassembly-3-2-0-now-available/

**Comment by AnoojNair** [comment]
Thank you. Will try it out

**Comment by AnoojNair** [comment]
@aslotte I guess only drawback would be that we won't be able to access user's file system to access the model file from a client app directly.

**Comment by aslotte** [comment]
I think this client will be consumed by anyone that uses it through a Docker Container running locally or in the cloud, so for anyone using local storage, they'll probably have to mount a drive that's accessible by the client. Definitely something we have to think of though.

**Comment by aslotte** [comment]
On today's stream we had some great input that in a wasm app everything is served in the browser, meaning we can't have connectionstrings etc. So we either need to add an API project or think of another solution to do this. Good thoughts :) 
I'm going to spend some time learning a bit about Blazor.

**Comment by danpdc** [comment]
It's actually the same thing as if you would develop an Angular or React app. Everything that needs to be done, should be done through the communication with a server because you can't have secrets in the app itself. I'm however not that familiar we what you actually want to do with this Blazor app, but as a baseline a client app should only consume data via an API and display it. A Blazor server project might make more sense if you want to connect to a lot of infrastructure, dowload files, nuget packages and so on. 

Size is also a problem in the Blazor client. If you download Nuget packages or whatever else you need, that would increase the app's footprint. Sure, files get cached by the browser, but size is still a problem.

**Comment by aslotte** [comment]
@danpdc yea, thanks for your input today! After reading up more on it, I do think a Blazor Server App makes more sense for our scenario, especially as the end goal is going to be delivering it as a Docker image.

**Comment by danpdc** [comment]
Totally agree. And I want to get involved. We'll get in touch tomorrow :)

**Comment by aslotte** [comment]
Thanks @danpdc! I may start on a skeleton myself just to learn more about Blazor (which is something I want to pick) but would your contributions!
