### ISSUE TITLE
[Deployment] Add SchemaGenerator class to dynamically generate ModelInput and ModelOutput class definitions

### ISSUE THREAD

**Issue by aslotte** [aslotte/MLOps.NET#302]
**Is your feature request related to a problem? Please describe.**
When we will deploy a model in a container, we need to dynamically generate the class definitions of the model input and model output classes.

**Describe the solution you'd like**
Create a `SchemaGenerator` class with a method `public string GenerateDefinition<T>(string className)`

The method should be able to generate and return a class definition as string including properties and custom attributes with values. The custom attributes we care about are `LoadColumn` and `ColumnName`.

**Update:** We probably want to call this method before deployment and store this in a data structure. E.g. I'm thinking `RegisterSchema<TInput, TOutput>()`

```
    public class ModelOutput
    {
        [ColumnName("PredictedLabel")]
        public bool Prediction { get; set; }

        [ColumnName("Score")]
        public float Score { get; set; }
    }
```

```
    public class ModelInput
    {
        [LoadColumn(0)]
        public bool Sentiment;

        [LoadColumn(1)]
        public string Review;
    }
```

**Pre-req** for #303

**Comment by AnoojNair** [comment]
@aslotte 
Something like this may be?
https://docs.microsoft.com/en-us/dotnet/framework/reflection-and-codedom/how-to-create-a-class-using-codedom

**Comment by AnoojNair** [comment]
@aslotte @Brett-Parker , i can give this one a try. Let me know if i can assign this to myself.

**Comment by aslotte** [comment]
Go for it @AnoojNair!

In essence, we need to store most if not all of the class definition if the database connected to a run.

**Comment by AnoojNair** [comment]
@aslotte , a couple of questions.

1. GenerateDefinition<T>(string className) function should take in the name of the class which will be eventually generated automagically? Should it also take in a list of name of properties and their type?

2 . Should the GenerateDefinition infer the ModelInput and ModelOutput from the data that is passed in and should it use the DataSchema and DataColumn class that we have already created and we have the type too.

3. If so Can we loop through the DataColumns and create a c# string representation?

**Comment by aslotte** [comment]
1. Correct, it's just so we can reuse it. The input will be `ModelInput` and `ModelOutput`
2. I thought about using DataColumns for this job, but I just wasn't able to figure out a good solution. 

Here's some of the challenges:
- We need to store any property decoration that may make sense. That includes `ColumnName`, `LoadColumn` and anything related to e.g. ONNX (I think they use Vector?). It may make sense to have a look at the community samples to see what we can expect from the `ModelOutput` in particular (I think for `ModelInput` the decorations are not so important but I'm not sure).
- We also need to be able to include namespaces. E.g. it's easy to guess that we'll need `Microsoft.ML.Data` for some of the attributes, but what about ONNX e.g.? I'm not sure how we can infer the namespaces from a passed in run-time instance, but that would be interesting to investigate

Let me know if that's helpful :)
