### ISSUE TITLE
[Deployment] Add ability to dynamically generate a ASP.NET Core Docker Image

### ISSUE THREAD

**Issue by aslotte** [aslotte/MLOps.NET#303]
**Is your feature request related to a problem? Please describe.**
We need to generate an ASP.NET Core Web API that's dynamic and takes a `ModelInput`, `ModelOutput` and a model.zip.
These three instances will be dynamically copied over based on the deployment, while the rest stays the same.

We need the ability to dynamically generate an image with these on demand, provided #302 is completed. 

**Depends** on #302 
**Pre-req** for #304 

**Describe the solution you'd like**
To be discussed.

- Can we generate a base image with the Web API on it and then copy over the remaining artifacts and re-build/re-publish?
- Can that base image be stored in Docker Hub? 
- What should the naming of the image be? Maybe `ExperimentName` with the tag being the `DeploymentId` Guid?

**Comment by SeanKilleen** [comment]
I might be able to help with this.

Idea: make use of `dotnet new` templates. Create template which includes dockerfile and some commands, add parameters for things like ML .NET version, publish location, etc. -- and then during the process call `dotnet new` which will generate the template using the parameters, at which time you should be able to copy over the files and then run `docker build` to actually build the container.

This is just first thoughts off the top of my head, as I'm not as familiar with the project (yet!) Let me know if you think that'd work.

**Comment by aslotte** [comment]
Love it @SeanKilleen! I think this will work nicely. I was thinking of how to include a project template in a useful way, and I think t makes a lot of sense to package them as nuget packages that can be installed, including templates that can be run using the CLI.

The use case is that a consumer of the library will call a method, e.g. `DeployModelToContainer<TInput, TOutput>(...)` that will essentially do a lot of stuff referenced #302, #304 and #305. We should be able to use e.g. CliWrap to execute the CLI command to install a template package created in another issue, run the `dotnet new` command, copy over schema classes from #302 and the the referenced model from our model repository. We can continue juggle some ideas here.

**Comment by aslotte** [comment]
I've broken out the `dotnet new` template generation to #307
