### ISSUE TITLE
[HacktoberFest] Create and prepare one or more issues for Hacktoberfest

### ISSUE THREAD

**Issue by aslotte** [aslotte/MLOps.NET#309]
**Is your feature request related to a problem? Please describe.**
Hacktoberfest kicks off every year to promote open source contributions: https://hacktoberfest.digitalocean.com/

**Describe the solution you'd like**
It would be fantastic if we can prepare and flush out one or more issues that are clearly defined so that we can tag them with the Hacktoberfest label and get additional people involved in the project.

**Comment by aslotte** [comment]
Opening up a thread here for suggestions on issues we can prepare for this event. Please feel free to suggest anything you can think of (new or existing issues)!

**Comment by willvelida** [comment]
@aslotte I was thinking about this! Definitely keen to use Hacktoberfest to work on some issues and new features! 😊

**Comment by aslotte** [comment]
Awesome! We can continue and brainstorm on some ideas 😄 
I think more isolated issues with a clear start and finish would be great candidates (e.g. adding a new column to a model or input validations of sorts)
