### ISSUE TITLE
[Deployment] Add ability to RegisterSchema

### ISSUE THREAD

**Issue by aslotte** [aslotte/MLOps.NET#360]
**Is your feature request related to a problem? Please describe.**
We currently have a SchemaGenerator but no way to store it.

**Describe the solution you'd like**
At the time at which someone would like to deploy a model to a container, they most likely don't have access to the input and output types. We need to store the types in a new table associated with the run.

I'm thinking a table called `ModelSchema` with columns:
- `ModelSchemaId`
- `RunId`
- `Name` (string, either ModelInput or ModelOutput)
- `Schema` (string)

I'm thinking a method called `RegisterSchema<TInput, TOutput>(Guid runId)`

**Comment by aslotte** [comment]
@AnoojNair if you're looking for a new issue, this would be a good one. I'm happy to pick it up otherwise.

**Comment by AnoojNair** [comment]
@aslotte Thanks, I will assign this to myself..

**Comment by AnoojNair** [comment]
@aslotte , do we need to pass in the name of the input and output class as parameters too for the register schema method as the schema generator expects a class name to be passed in.

**Comment by aslotte** [comment]
No need for the user to pass that in, as they need to be the same every time (`ModelInput` and `ModelOutput`) for the dotnet new project template to compile. We'll just pass that in separately when using the SchemaGenerator

**Comment by aslotte** [comment]
@AnoojNair just checking in if you need any help with this issue. I think it may be the final one for v1.2 apart from stability testing and potentially some smaller tweaks :)
