### ISSUE TITLE
Update to .NET 5 and C# 9

### ISSUE THREAD

**Issue by aslotte** [aslotte/MLOps.NET#365]
**Is your feature request related to a problem? Please describe.**
We want to be using the latest technology.

**Describe the solution you'd like**
Update all projects to MLOps.NET to .NET 5

**Comment by RonaldMariah** [comment]
@aslotte Happy to take this and create a PR.

**Comment by aslotte** [comment]
Thanks @RonaldMariah - feel free to have a stab at it!
