### ISSUE TITLE
CreateExperiment creates duplicates in Azure Storage

### ISSUE THREAD

**Issue by aslotte** [aslotte/MLOps.NET#48]
**Describe the bug**
When calling  `CreateExperiment` duplicate experiments are creating if one with the same name already exists in Azure TableStorage

**To Reproduce**
1. Call CreateExperiment two times in a row using Azure Storage

**Expected behavior**
I would expect that if an experiment with the same name already exist that no new experiment is created and rather the existing one's id is returned

**Comment by lqdev** [comment]
I can do this one
