### ISSUE TITLE
Add web client to visualize experiments, runs and metrics

### ISSUE THREAD

**Issue by aslotte** [aslotte/MLOps.NET#6]
Create a simple Blazor App with a RESTful Web API backing it

**Comment by aslotte** [comment]
This should probably be hosted in a Docker container one can pull and run locally with the following input:

- Storage type (Azure, local, AWS)
- Connectionstring

**Comment by dcostea** [comment]
@aslotte , do you consider having a webapi to get data from? If it's yes, are you thinking of WebAPI REST or MVC?

**Comment by aslotte** [comment]
Great thoughts @dcostea. My initial idea behind this ticket was not a separate API to be honest. What I was thinking with this ticket was a:
- A Web API with business logic to communicate with given storage provider
- A Blazor app sitting on top
- All packaged in to a container that only takes type of storage provider and connection string when spun up

Like that anyone using this solution to vizualize their metrics only need to pull the Docker image from a repository, provide the connection info to their data and start the container and navigate to e.g. `localhost:5000`

With that said, there may be an added value on a separate RESTful API as well for automation purposes, but I was thinking the most of that would be in the SDK itself (e.g. adding or pulling metrics etc.). I'm very much open for discussion on that though.

**Comment by aslotte** [comment]
I also realize that this is a massive issue, and we may want to break this down into much smaller issues, so we can constructively work on it :)

**Comment by AnoojNair** [comment]
@aslotte , just thinking how about to start with have a pynb file which connects to mlops and we can use a chart library to have a dashboard? As a starting point?

**Comment by aslotte** [comment]
I think we should off on this issue for a bit longer. I'm thinking we should build out a full Blazor Web App running in a Docker Container for this. It's going to need some planning.
