### ISSUE TITLE
Add workflow to publish packages to nuget.org

### ISSUE THREAD

**Issue by aslotte** [aslotte/MLOps.NET#66]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**
Add GitHub workflow to publish packages from a release branch to nuget.org

**Describe alternatives you've considered**

**Additional context**

**Comment by aslotte** [comment]
I'm thinking that it would be awesome if the workflow would
- Add a release tag to the master branch
- Create a GitHub release
- Build the master branch, run unit tests and create packages with provided version number
- Push to nuget.org

**Comment by Brett-Parker** [comment]
https://lukelowrey.com/use-github-actions-to-publish-nuget-packages/ - For reference. Think this likely needs to be setup by you @aslotte . Looks like a lot of administrator privileges.

**Comment by aslotte** [comment]
This is probably useful as well https://github.com/actions/create-release

**Comment by aslotte** [comment]
We could use this to get the build number https://github.com/dotnet/nbgv from Nerdbank.GitVersioning
Question is if we can also set the build number using it
