### ISSUE TITLE
Add an MLOpsBuilder to create a configured instance of MLLifeCycleManager

### ISSUE THREAD

**Issue by ssa3512** [aslotte/MLOps.NET#70]
**Is your feature request related to a problem? Please describe.**
The initial setup of `MLLifeCycleManager` for small test scenarios seems problematic in that you are required to set up a backing store before using or it throws an exception. It seems to me there should be a default implementation that requires zero configuration, perhaps an in-memory dictionary based store.

**Describe the solution you'd like**
Add in-memory store implementations of `IMetaDataStore` and `IModelRepository` - these will be useful for testing various scenarios in which the user does not need to persist the data in a permanent storage mechanism. Make these the default implementation instead of throwing an exception via `EnsureStorageProviderConfigured` on every call to `MLLifeCycleManager`

**Describe alternatives you've considered**
Alternatively could use SQLite implementation as default as it does not require any configuration by default, however it does persist on disk which might be undesirable for testing various scenarios.

**Additional context**
N/A

**Comment by aslotte** [comment]
Thank you for opening this issue @ssa3512. I agree that it's not optimal to have to check if the providers have been set up correctly in each method. Regarding in-memory providers, I think given that it doesn't have a meaningful usage for this tool (e.g. the idea is to track things look term, so we need persistence) and it may also confuse a user as it will "work" without setting up the provider it may not be an optimal approach.

However, we should think about other ways we can wire it up though so it's easier to use. 
An idea would be to make the parameterless ctor private and expose something like this that would enforce the user them explicitly. A benefit with this is that you have metadata in Azure and models stored locally for example or vice versa. We could also brainstorm on other solutions, or one that involves wrapper objects.

```
        public MLLifeCycleManager(IModelRepository modelRepository, IMetaDataStore metaDataStore)
        {
            this.ModelRepository = modelRepository;
            this.MetaDataStore = metaDataStore;
        }
```

**Comment by ssa3512** [comment]
I definitely think exposing a constructor that allows you to pass in the dependencies is worthwhile - it will allow for unit testing using mocks, as well as allowing consumers to pass in their own implementations if desired.

If you want to require these to be setup, perhaps implementing a chained builder style setup that fails immediately (ultimately via a null check in the constructor) might be better.

Something like this:
``` cs
IMLLifeCycleManager lcManager = new MLOpsBuilder()
    .UseAzureStorage()
    .Build()
```
You could then add `UseMetaDataStore` and `UseModelRepository` extensions that allow the consumer to pass in values or create via a Func. The builder could also detect if multiple items were configured for either dependency and throw an exception if you try to configure two different implementations of one. Right now you end up with unexpected behavior if you do `new MLLifeCycleManager().UseSQLite().UseAzureStorage() since only one can be configured at a time.

**Comment by aslotte** [comment]
Yes, yes and yes. I think this will work nicely, meet the extensibility needs we have plus make sense from a product stand-point. 👍

**Comment by ssa3512** [comment]
If you want to assign to me I can work on this.

**Comment by aslotte** [comment]
Assigned. Thanks! I updated the title slightly, feel free to edit as needed.
