### ISSUE TITLE
Tracking hyperparameters associated with a run.

### ISSUE THREAD

**Issue by AnoojNair** [aslotte/MLOps.NET#76]
**Is your feature request related to a problem? Please describe.**
Along with capturing the run and the corresponding metrics , we should capture Run duration as well. 
Also is there a way to log hyperparameters used to train a model the same we log the metrics using a generic method?  Is there a method or property on ml.net which returns a list of hyperparameters?

**Describe the solution you'd like**
Add 2 new properties for capturing run duration and hyperparameters on the Run class

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by lqdev** [comment]
One thing to consider is the AutoML API. That feature is already built in. From a user standpoint, whether they manually calculate this or whether it's something provided through the AutoML API, logging should be generic enough to be able to handle both cases.

**Comment by aslotte** [comment]
Great thoughts @AnoojNair  and @lqdev. My 2 cents on training time, would it make sense to belong on the table entity or as a key-value pair in the metric's table?

**Comment by AnoojNair** [comment]
Thank you @lqdev @aslotte . I feel training time would be a part of the Run class , as Metrics bring me to my mind the model metrics .

I feel i should open a new issue to handle training time and Hyper parameters separately. Opened a new issue #81 to track training time.
