### ISSUE TITLE
Add setup instructions on how to get started with the repo

### ISSUE THREAD

**Issue by aslotte** [aslotte/MLOps.NET#83]
**Is your feature request related to a problem? Please describe.**
To get started with the repo, we should provide instructions or scripts to install all dependencies needed to run unit/integration tests and build the project.

E.g.
- Setup SQLite (script or instructions)
- Setup Azure Storage Account (ARM Template)

**Comment by aslotte** [comment]
Maybe we could provide the new code spaces in GitHub

**Comment by Brett-Parker** [comment]
I'm going through this process now. I'd be happy to document it as I go. Can you assign to me? I am unable to assign for some reason.

**Comment by aslotte** [comment]
Thank @Brett-Parker, that would be awesome! Assigned it to you.

**Comment by aslotte** [comment]
We have a Wiki page that intructs how to get started with the repo so I'm going to close this issue.
