### ISSUE TITLE
Update MLLifecycleManager to expose builder overload for UseAzureBlobStorage

### ISSUE THREAD

**Issue by aslotte** [aslotte/MLOps.NET#9]
Instead of passing in the connectionstring in the constructor, let's use a method, e.g.

```
public MLLifecycleManger UseAzureBlobStorage(string connectionString) 
{
     //do stuff here
     return this;
}

**Comment by AnoojNair** [comment]
Hi @aslotte , Just curious how you intended to be used?
Would it be like below?

MLLifecycleManger manager = new MLLifecycleManger();
manager.UseAzureBlobStorage(connString);

Are there plans to support other types of storage?

**Comment by aslotte** [comment]
Hi @AnoojNair - great questions, so I'm envisioning something like this with method chaining

```
var manager = new MLLifecycleManager().UseAzureStorage(connectionString);
```
We're currently trying to use the simplest approach possible that will work when integrated into a GitHub action, thus an Azure Storage account is used (Blob storage for the model and a NoSQL Table Storage to store the metadata). We would also eventually need to store local mode, and I was envisioning a fileshare and a SQL database at that point but is totally open for ideas :)

**Comment by aslotte** [comment]
With that said, I think it would be awesome if we can have this as a separate project (package). For example it could be named `MLOps.NET.Azure`

**Comment by aslotte** [comment]
@AnoojNair would you like me to assign this issue to you to work on? Just want to make sure I don't accidentally work on it during my stream tomorrow if you want to have a look at it :)

**Comment by AnoojNair** [comment]
Hi @aslotte , Yes sure you can assign it to me.

**Comment by aslotte** [comment]
Thanks @AnoojNair!
