### ISSUE TITLE
Capture the confusion matrix in a classification scenario

### ISSUE THREAD

**Issue by aslotte** [aslotte/MLOps.NET#94]
**Is your feature request related to a problem? Please describe.**
We currently have no way of storing the confusion matrix of a classification run, we'll need to add support for this.

**Describe the solution you'd like**
I think we need a new entity for this to store. A confusion matrix is coupled with a run.

**Describe alternatives you've considered**

**Additional context**

**Comment by AnoojNair** [comment]
@aslotte  , the ConfusionMatrix class does expose a method which returns a nicely formatted table representation of the matrix in the form of a string,  How about we store that one?
